// GERADO por tools/extract_kemper_nrpn.mjs a partir de NRPN_KEMPER.h.
// NAO editar a mao. Sao os CCs especiais do Kemper (NRPN) que o firmware
// realmente trata — aparecem na lista de CC dos SW so em MODO KEMPER PLAYER.

export const KEMPER_NRPN_CCS = [
  { value: 200, label: "TRANSPOSE ON-OFF", group: "onoff" },
  { value: 201, label: "NOISE GATE ON-OFF", group: "onoff" },
  { value: 202, label: "COMPRESSOR ON-OFF", group: "onoff" },
  { value: 203, label: "PURE BOOSTER ON-OFF", group: "onoff" },
  { value: 204, label: "WAH-WAH ON-OFF", group: "onoff" },
  { value: 205, label: "VINTAGE CHORUS ON-OFF", group: "onoff" },
  { value: 206, label: "AIR CHORUS ON-OFF", group: "onoff" },
  { value: 207, label: "DOBLE TRACKER ON-OFF", group: "onoff" },
  { value: 208, label: "Pitch Transpose", group: "param" },
  { value: 209, label: "NG Threshold", group: "param" },
  { value: 210, label: "NG Decay", group: "param" },
  { value: 211, label: "Comp Threshold", group: "param" },
  { value: 212, label: "PB Volume", group: "param" },
  { value: 213, label: "Wah Pedal Mode", group: "param" },
  { value: 214, label: "VC Range", group: "param" },
  { value: 215, label: "VC Depth", group: "param" },
  { value: 216, label: "VC Mix", group: "param" },
  { value: 217, label: "AC Depth", group: "param" },
  { value: 218, label: "AC Mix", group: "param" },
  { value: 219, label: "DT Looseness", group: "param" },
  { value: 220, label: "DT Stereo", group: "param" },
  { value: 224, label: "Delay LowCut", group: "param" },
  { value: 225, label: "Delay HighCut", group: "param" },
  { value: 226, label: "Delay Ducking", group: "param" },
  { value: 227, label: "Delay Mod", group: "param" },
  { value: 228, label: "Delay Flutter Intensity", group: "param" },
  { value: 231, label: "Reverb Predelay", group: "param" },
  { value: 232, label: "Reverb LowCut", group: "param" },
  { value: 233, label: "Reverb HighCut", group: "param" },
  { value: 234, label: "Reverb Mod", group: "param" },
  { value: 235, label: "Reverb Ducking", group: "param" },
  { value: 236, label: "Mod Rate", group: "param" },
  { value: 237, label: "Mod Depth", group: "param" },
  { value: 238, label: "Mod Feedback", group: "param" },
  { value: 239, label: "Mod Mix", group: "param" },
  { value: 240, label: "Slot A Mix", group: "param" },
  { value: 241, label: "Slot A Drive", group: "param" },
  { value: 242, label: "Slot A Tone", group: "param" },
  { value: 243, label: "Slot A Ducking", group: "param" },
  { value: 244, label: "Slot B Mix", group: "param" },
  { value: 245, label: "Slot B Drive", group: "param" },
  { value: 246, label: "Slot B Tone", group: "param" },
  { value: 247, label: "Slot B Ducking", group: "param" },
  { value: 248, label: "Slot C Mix", group: "param" },
  { value: 249, label: "Slot C Drive", group: "param" },
  { value: 250, label: "Slot C Tone", group: "param" },
  { value: 251, label: "Slot C Ducking", group: "param" },
  { value: 252, label: "Slot D Mix", group: "param" },
  { value: 253, label: "Slot D Drive", group: "param" },
  { value: 254, label: "Slot D Tone", group: "param" },
  { value: 255, label: "Slot D Ducking", group: "param" },
  { value: 256, label: "Slot X Mix", group: "param" },
  { value: 257, label: "Slot X Drive", group: "param" },
  { value: 258, label: "Slot X Tone", group: "param" },
  { value: 259, label: "Slot X Ducking", group: "param" },
  { value: 260, label: "Amp On/Off", group: "param" },
  { value: 261, label: "Amp Volume", group: "param" },
  { value: 263, label: "Amp Clean Comp", group: "param" },
  { value: 264, label: "Amp Definition", group: "param" },
  { value: 265, label: "Amp Clarity", group: "param" },
  { value: 266, label: "Amp Power Sag", group: "param" },
  { value: 267, label: "Amp Pick", group: "param" },
  { value: 268, label: "Amp Compressor", group: "param" },
  { value: 269, label: "Amp Tube Shape", group: "param" },
  { value: 270, label: "Amp Tube Bias", group: "param" },
  { value: 271, label: "Amp Gain Pot Ref", group: "param" },
  { value: 272, label: "Amp Model Gain", group: "param" },
  { value: 273, label: "Amp Direct Mix", group: "param" },
  { value: 274, label: "Amp Bright Cap", group: "param" },
  { value: 275, label: "EQ Bass", group: "param" },
  { value: 276, label: "EQ Middle", group: "param" },
  { value: 277, label: "EQ Treble", group: "param" },
  { value: 278, label: "EQ Presence", group: "param" },
  { value: 279, label: "EQ Position", group: "param" },
  { value: 280, label: "Cab On/Off", group: "param" },
  { value: 281, label: "Cab High Shift", group: "param" },
  { value: 282, label: "Cab Low Shift", group: "param" },
  { value: 283, label: "Cab Character", group: "param" },
  { value: 284, label: "Cab Pure Cab", group: "param" },
  { value: 285, label: "Cab Kone Imprint", group: "param" },
  { value: 286, label: "Cab Low Cut", group: "param" },
  { value: 287, label: "Cab High Cut", group: "param" },
  { value: 289, label: "Delay Tempo Sync", group: "param" },
  { value: 291, label: "Delay Freeze", group: "param" },
  { value: 292, label: "Delay Cut Char", group: "param" },
  { value: 293, label: "Delay Ducking Pos", group: "param" },
  { value: 294, label: "Delay Note Val 1", group: "param" },
  { value: 295, label: "Delay Note Val 2", group: "param" },
  { value: 297, label: "Reverb Position", group: "param" },
  { value: 298, label: "Reverb Tempo Sync", group: "param" },
  { value: 299, label: "Reverb Freeze", group: "param" },
  { value: 300, label: "Reverb Infinity", group: "param" },
  { value: 301, label: "Reverb Reverse", group: "param" },
  { value: 302, label: "Reverb Ducking Pos", group: "param" },
  { value: 303, label: "Reverb Predelay Note", group: "param" },
  { value: 306, label: "Delay Stereo", group: "param" },
  { value: 307, label: "Delay Chorus", group: "param" },
  { value: 308, label: "Delay Reverse Mix", group: "param" },
  { value: 309, label: "Delay Flutter Rate", group: "param" },
  { value: 310, label: "Delay Grit", group: "param" },
  { value: 311, label: "Delay Input Swell", group: "param" },
  { value: 312, label: "Delay Smear", group: "param" },
  { value: 314, label: "Reverb Volume", group: "param" },
  { value: 315, label: "Reverb Stereo", group: "param" },
  { value: 316, label: "Reverb Size", group: "param" },
  { value: 317, label: "Reverb Density", group: "param" },
  { value: 318, label: "Reverb Diffusion", group: "param" },
  { value: 319, label: "Reverb Mod Rate", group: "param" },
  { value: 320, label: "Reverb Mod Depth", group: "param" },
  { value: 321, label: "Reverb Smear", group: "param" },
];
